///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest5
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest5Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("04f203cf-482d-4add-8c13-3681543c3fad")]
    public partial class MyTest5Repository : RepoGenBaseFolder
    {
        static MyTest5Repository instance = new MyTest5Repository();
        MyTest5RepositoryFolders.ShellEnvAppFolder _shellenv;
        MyTest5RepositoryFolders.TestHash4ConsoleJenkinsAppFolder _testhash4consolejenkins;
        MyTest5RepositoryFolders.TaskSwitchingAppFolder _taskswitching;
        MyTest5RepositoryFolders.AeroScoutEngineManagerAppFolder _aeroscoutenginemanager;
        MyTest5RepositoryFolders.EngineManagerAppFolder _enginemanager;
        MyTest5RepositoryFolders.RxSupportSalesforceAppFolder _rxsupportsalesforce;

        /// <summary>
        /// Gets the singleton class instance representing the MyTest5Repository element repository.
        /// </summary>
        [RepositoryFolder("04f203cf-482d-4add-8c13-3681543c3fad")]
        public static MyTest5Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest5Repository() 
            : base("MyTest5Repository", "/", null, 0, false, "04f203cf-482d-4add-8c13-3681543c3fad", ".\\RepositoryImages\\MyTest5Repository04f203cf.rximgres")
        {
            _shellenv = new MyTest5RepositoryFolders.ShellEnvAppFolder(this);
            _testhash4consolejenkins = new MyTest5RepositoryFolders.TestHash4ConsoleJenkinsAppFolder(this);
            _taskswitching = new MyTest5RepositoryFolders.TaskSwitchingAppFolder(this);
            _aeroscoutenginemanager = new MyTest5RepositoryFolders.AeroScoutEngineManagerAppFolder(this);
            _enginemanager = new MyTest5RepositoryFolders.EngineManagerAppFolder(this);
            _rxsupportsalesforce = new MyTest5RepositoryFolders.RxSupportSalesforceAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("04f203cf-482d-4add-8c13-3681543c3fad")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ShellEnv folder.
        /// </summary>
        [RepositoryFolder("6de9f9a0-8f81-45bf-94a9-223c65223ad3")]
        public virtual MyTest5RepositoryFolders.ShellEnvAppFolder ShellEnv
        {
            get { return _shellenv; }
        }

        /// <summary>
        /// The TestHash4ConsoleJenkins folder.
        /// </summary>
        [RepositoryFolder("ba59a9f5-4879-423f-adf0-2d6aba82fbab")]
        public virtual MyTest5RepositoryFolders.TestHash4ConsoleJenkinsAppFolder TestHash4ConsoleJenkins
        {
            get { return _testhash4consolejenkins; }
        }

        /// <summary>
        /// The TaskSwitching folder.
        /// </summary>
        [RepositoryFolder("cda8a4a3-67ce-4594-b073-c490a85cb3e1")]
        public virtual MyTest5RepositoryFolders.TaskSwitchingAppFolder TaskSwitching
        {
            get { return _taskswitching; }
        }

        /// <summary>
        /// The AeroScoutEngineManager folder.
        /// </summary>
        [RepositoryFolder("c8aff360-3ec5-45cc-826f-c195110fa13f")]
        public virtual MyTest5RepositoryFolders.AeroScoutEngineManagerAppFolder AeroScoutEngineManager
        {
            get { return _aeroscoutenginemanager; }
        }

        /// <summary>
        /// The EngineManager folder.
        /// </summary>
        [RepositoryFolder("a901ac4a-193f-4c59-8a10-58eb9aab9861")]
        public virtual MyTest5RepositoryFolders.EngineManagerAppFolder EngineManager
        {
            get { return _enginemanager; }
        }

        /// <summary>
        /// The RxSupportSalesforce folder.
        /// </summary>
        [RepositoryFolder("05d48cbd-1d1a-4de5-8e27-e3dec455fcc0")]
        public virtual MyTest5RepositoryFolders.RxSupportSalesforceAppFolder RxSupportSalesforce
        {
            get { return _rxsupportsalesforce; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTest5RepositoryFolders
    {
        /// <summary>
        /// The ShellEnvAppFolder folder.
        /// </summary>
        [RepositoryFolder("6de9f9a0-8f81-45bf-94a9-223c65223ad3")]
        public partial class ShellEnvAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _testtemplateInfo;

            /// <summary>
            /// Creates a new ShellEnv  folder.
            /// </summary>
            public ShellEnvAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ShellEnv", "/form[@controlname='ShellEnv']", parentFolder, 30000, null, true, "6de9f9a0-8f81-45bf-94a9-223c65223ad3", "")
            {
                _testtemplateInfo = new RepoItemInfo(this, "TestTemplate", "container[@controlname='_pnlLeft']/container[@controlname='_pnlDetails']/container[@controlname='_myTabControl']/element/element/container/container/container/tabpagelist/tabpage[@title='Templates']/container[@automationid='TemplatesViewTab']/container/table/container/element/element/container/container[2]/row[@index='8']/container/container/element/container/cell[@text='TestTemplate']", "", 30000, null, "89134210-5c80-4f6e-948c-b993c5ef08e5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6de9f9a0-8f81-45bf-94a9-223c65223ad3")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6de9f9a0-8f81-45bf-94a9-223c65223ad3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TestTemplate item.
            /// </summary>
            [RepositoryItem("89134210-5c80-4f6e-948c-b993c5ef08e5")]
            public virtual Ranorex.Cell TestTemplate
            {
                get
                {
                    return _testtemplateInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The TestTemplate item info.
            /// </summary>
            [RepositoryItemInfo("89134210-5c80-4f6e-948c-b993c5ef08e5")]
            public virtual RepoItemInfo TestTemplateInfo
            {
                get
                {
                    return _testtemplateInfo;
                }
            }
        }

        /// <summary>
        /// The TestHash4ConsoleJenkinsAppFolder folder.
        /// </summary>
        [RepositoryFolder("ba59a9f5-4879-423f-adf0-2d6aba82fbab")]
        public partial class TestHash4ConsoleJenkinsAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new TestHash4ConsoleJenkins  folder.
            /// </summary>
            public TestHash4ConsoleJenkinsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("TestHash4ConsoleJenkins", "/dom[@domain='localhost:8080']", parentFolder, 30000, null, false, "ba59a9f5-4879-423f-adf0-2d6aba82fbab", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ba59a9f5-4879-423f-adf0-2d6aba82fbab")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ba59a9f5-4879-423f-adf0-2d6aba82fbab")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The TaskSwitchingAppFolder folder.
        /// </summary>
        [RepositoryFolder("cda8a4a3-67ce-4594-b073-c490a85cb3e1")]
        public partial class TaskSwitchingAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new TaskSwitching  folder.
            /// </summary>
            public TaskSwitchingAppFolder(RepoGenBaseFolder parentFolder) :
                    base("TaskSwitching", "/form[@title='Task Switching']", parentFolder, 30000, null, true, "cda8a4a3-67ce-4594-b073-c490a85cb3e1", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cda8a4a3-67ce-4594-b073-c490a85cb3e1")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cda8a4a3-67ce-4594-b073-c490a85cb3e1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The AeroScoutEngineManagerAppFolder folder.
        /// </summary>
        [RepositoryFolder("c8aff360-3ec5-45cc-826f-c195110fa13f")]
        public partial class AeroScoutEngineManagerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _helpInfo;

            /// <summary>
            /// Creates a new AeroScoutEngineManager  folder.
            /// </summary>
            public AeroScoutEngineManagerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AeroScoutEngineManager", "/form[@title='AeroScout Engine Manager']", parentFolder, 30000, null, true, "c8aff360-3ec5-45cc-826f-c195110fa13f", "")
            {
                _helpInfo = new RepoItemInfo(this, "Help", "menubar[@accessiblename='Application']/menuitem[@accessiblename='Help']", "", 30000, null, "b5b896c9-8112-476a-a03f-4e8d1acff68e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c8aff360-3ec5-45cc-826f-c195110fa13f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c8aff360-3ec5-45cc-826f-c195110fa13f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Help item.
            /// </summary>
            [RepositoryItem("b5b896c9-8112-476a-a03f-4e8d1acff68e")]
            public virtual Ranorex.MenuItem Help
            {
                get
                {
                    return _helpInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Help item info.
            /// </summary>
            [RepositoryItemInfo("b5b896c9-8112-476a-a03f-4e8d1acff68e")]
            public virtual RepoItemInfo HelpInfo
            {
                get
                {
                    return _helpInfo;
                }
            }
        }

        /// <summary>
        /// The EngineManagerAppFolder folder.
        /// </summary>
        [RepositoryFolder("a901ac4a-193f-4c59-8a10-58eb9aab9861")]
        public partial class EngineManagerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _aeroscoutenginemanagerhelpInfo;

            /// <summary>
            /// Creates a new EngineManager  folder.
            /// </summary>
            public EngineManagerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("EngineManager", "/contextmenu[@processname='EngineManager']", parentFolder, 30000, null, false, "a901ac4a-193f-4c59-8a10-58eb9aab9861", "")
            {
                _aeroscoutenginemanagerhelpInfo = new RepoItemInfo(this, "AeroScoutEngineManagerHelp", "contextmenu/menuitem[@accessiblename>'AeroScout Engine Manager']", "", 30000, null, "d9ff5564-76a3-419f-9630-69affddcb97f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a901ac4a-193f-4c59-8a10-58eb9aab9861")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a901ac4a-193f-4c59-8a10-58eb9aab9861")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AeroScoutEngineManagerHelp item.
            /// </summary>
            [RepositoryItem("d9ff5564-76a3-419f-9630-69affddcb97f")]
            public virtual Ranorex.MenuItem AeroScoutEngineManagerHelp
            {
                get
                {
                    return _aeroscoutenginemanagerhelpInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The AeroScoutEngineManagerHelp item info.
            /// </summary>
            [RepositoryItemInfo("d9ff5564-76a3-419f-9630-69affddcb97f")]
            public virtual RepoItemInfo AeroScoutEngineManagerHelpInfo
            {
                get
                {
                    return _aeroscoutenginemanagerhelpInfo;
                }
            }
        }

        /// <summary>
        /// The RxSupportSalesforceAppFolder folder.
        /// </summary>
        [RepositoryFolder("05d48cbd-1d1a-4de5-8e27-e3dec455fcc0")]
        public partial class RxSupportSalesforceAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _somedivtagInfo;

            /// <summary>
            /// Creates a new RxSupportSalesforce  folder.
            /// </summary>
            public RxSupportSalesforceAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxSupportSalesforce", "/dom[@domain='na158.lightning.force.com']", parentFolder, 30000, null, false, "05d48cbd-1d1a-4de5-8e27-e3dec455fcc0", "")
            {
                _somedivtagInfo = new RepoItemInfo(this, "SomeDivTag", "body/div[4]/div[1]/section/div[1]/div/div[2]/div[2]/section[7]/div/div/section/div/div[2]/div/div/div/div[2]/iframe//div[#'main']/div/div[1]/div/div/div/div[1]/div[2]/div[2]/div[3]/div/article/div[1]/div/div[1]/div/div[1]", "", 30000, null, "71586817-4c88-4852-8fc2-7b6ae5bfe21e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("05d48cbd-1d1a-4de5-8e27-e3dec455fcc0")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("05d48cbd-1d1a-4de5-8e27-e3dec455fcc0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SomeDivTag item.
            /// </summary>
            [RepositoryItem("71586817-4c88-4852-8fc2-7b6ae5bfe21e")]
            public virtual Ranorex.DivTag SomeDivTag
            {
                get
                {
                    return _somedivtagInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SomeDivTag item info.
            /// </summary>
            [RepositoryItemInfo("71586817-4c88-4852-8fc2-7b6ae5bfe21e")]
            public virtual RepoItemInfo SomeDivTagInfo
            {
                get
                {
                    return _somedivtagInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
